openapi: 3.0.1
info:
  title: monster-juiblex
  x-cortex-tag: monster-juiblex
  x-cortex-custom-metadata:
    alignment: chaotic-evil
    type: fiend
    challenge_rating: 12
    legendary: true
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-juiblex
      alias: github-token-test
